### ISSUE TITLE
 As a member, I want to add custom URLs to my community view so that I can quickly access the websites/apps I use often, even though they are not community tools that everyone else uses for the class.

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#100]
add custom url
- [x] mockups
- [ ] front-end
- [ ] back-end

edit custom url
- [ ] mockups
- [ ] front-end
- [ ] back-end

rename custom url
- [ ] mockups
- [ ] front-end
- [ ] back-end

explain to leader what this does and doesn't do (doesn't provision anything)
- [x] mockups
- [ ] front-end
- [ ] back-end

remove custom url
- [x] mockups
- [ ] front-end
- [ ] back-end

Stretch
- [ ] add custom url to multiple communities at once
- [ ] system searches app store to ensure the custom url isn't already integrated with the system
- [ ] upload a file as a custom url

**Comment by swwalker** [comment]
closed - incorporated in #221 and #224
