### ISSUE TITLE
As a leader, I want to export group membership to CSV so that I can import users into a non-integrated tool

### ISSUE THREAD

**Issue by chrislorch** [DukeLearningInnovation/kits#109]
Value of this simple feature was articulated by Michael Faber in early meeting.

Stretch
- [ ] leader clicks export members
- [ ] csv downloaded with headers. columns for name, eppn, role, official vs manually added status
- [ ] system log generated so admins know how often this feature is used.

**Comment by mccahill** [comment]
CSV export should include the role(s) for each user so that the roles defined within the community can be used to provision individuals with appropriate capabilities.

**Comment by swwalker** [comment]
closed - incorporated in #199
