### ISSUE TITLE
As an authenticated user, I want to organize my communities so I can find the one i'm looking for

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#136]
- [ ] filter communities by name
- [ ] sort communities by name
- [ ] sort communites by category (course vs non course for ex)

**Comment by swwalker** [comment]
Implementation of this feature will require team to revisit how card color is assigned.  See #207 for discussion of color assignment from MVP1.

**Comment by swwalker** [comment]
For MVP1, team agreed to address sorting by course number and course title.  Sorting by course role, sorting by category and all filtering will be deferred to a future release based on user feedback.

**Comment by swwalker** [comment]
Closing issue - user story incorporated in #188 View My Course Communities.  Implementing sort by course number, sort by course title, and filter by semester.

Based on user testing/feedback, new enhancement issues will be added to include additional sort and/or filter criteria.
