### ISSUE TITLE
As a leader, I want to hide tools from members so I can configure the tool before they access it

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#141]
- [ ] on/off slider type of ui for show/hide

Stretch
- [ ] notify community members when a new tool is available
- [ ] all leaders to set a future date when the tool becomes available

**Comment by swwalker** [comment]
closed - incorporated in #198 and #236
