### ISSUE TITLE
As a member, I want to share a custom url with others

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#144]
- [ ] select url to edit
- [ ] select share
- [ ] select who to share with. community leaders so they can share it with the entire community or to individual community members
- [ ] select share
- [ ] leaders or members receive notification of shared url
- [ ] leaders or members confirm add or do not add shared custom url

**Comment by swwalker** [comment]
Closed - incorporated in #236
