### ISSUE TITLE
As an admin, I run one of the system reports so that I can analyze system usage

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#148]
- [ ] view list of default reports
- [ ] select report
- [ ] run report

Stretch
- [ ] search for a specific report
- [ ] export report to PDF
- [ ] export raw data used to generate report
- [ ] request a custom report

**Comment by profmikegreene** [comment]
Closing for now. Lets focus on in-browser analytics, not PDF exports.
