### ISSUE TITLE
As a leader, I want to review how members use the community so that I can improve it

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#149]
- [ ] what custom urls members add
- [ ] what custom labels members use
- [ ] activity streams (sakai statistics)

**Comment by profmikegreene** [comment]
incorporated into #203 problem statment
