### ISSUE TITLE
Piazza Integration

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#170]
- [x] outline goals of the integration
### Add app
1. User clicks add app and selects Piazza in the app store
2. Kits sends LTI POST request to Piazza
3. User taken to Piazza's  'Link to Piazza' screen
4. User selects create class or search
5. If Piazza supports LTI Memberships, add all kits members at once, otherwise, members will be added the first time they click to launch Piazza from the kit.

#### Rename
1. Instructor goes into kit edit mode
2. Instructor renames Piazza and clicks done
3. Kits updates the Piazza site name in Piazza

#### Toggle Visibility
1. Instructor goes into kit edit mode
2. Instructor toggles visibility of app to students

### Remove app
1. Instructor goes into kit edit mode
2. Instructor selects the option to remove Piazza
3. If Piazza supports LTI Memberships, Kits removes all users in the kit from the Piazza site, Kits does not delete the library
4. Kits removes the app from the kit card UI

- [x] map roles

Kits UI  Display | Kits Role | Piazza Role
-- | -- | --
Instructor | Leader  | Professor
Assistant | Assistant | TA
Student | Participant | Student
Visitor | Visitor | Student

- [x] explore API's ability to accomplish goals
- [x] build a proof of concept

**Comment by profmikegreene** [comment]
There doesn't seem to be an official REST API for Piazza, perhaps emailing integrations@piazza.com would get us some insider access. If not, Piazza will be a good example of how this service could leverage LTI instead.

1. community leader clicks add Piazza
1. user taken to 'Link to Piazza' screen
<img width="1243" alt="sakai___usermembershiptest___piazza" src="https://user-images.githubusercontent.com/3632822/39776589-4740a300-52cf-11e8-982d-048df301796c.png">
1. user selects create class or search

Because this is LTI, not much logic happens on our end. If Piazza supports LTI Memberships, we could add all community members at once, otherwise, members will be added the first time they click to launch piazza.

How that look to you @chrislorch ?

https://piazza.com/product/lti
https://s3.amazonaws.com/piazza-materials/LTI-Setup/GetAProgrammerStartedWithLTI.pdf
