### ISSUE TITLE
View My Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#188]
### Description
An authenticated user is directed to a dashboard view of their course communities.  

- Courses will be displayed in grid view
- Default view is current semester courses
- Default course order is ascending by course number

### User Stories

1. As an authenticated user, I access the tools for my courses throughout the semester from this app so that I can launch tools more conveniently #106
2. As an authenticated user, I want to organize my communities so I can find the one i'm looking for #136

### Questions
- [x] How should cross-listed courses be displayed? #205

### Tasks
- [x] Decide how color will be applied to communities #207
- [x] Implement either search or sort on communities by course number and name #241 
- [x] Design verification
- [x] Functional verification

### Updates from design QA

- [x] Hover over the "Fall 2018" shows this weird hover state. Should have to dropdown icon/arrow if more semesters to view
- [ ] Card title: #001a57, Open Sans, add letter-spacing: 1px-1.2px, bold #315
- [x] The app tiles are squished at certain break points.
- [x] App tiles should be smaller at 60x60
- [x] Potentially the "add app" icon could be even smaller at 40x40
![image](https://user-images.githubusercontent.com/38253046/46313530-169db280-c596-11e8-856d-d47786df8697.png)

- [x] Pull semester into course number display #258
- [x] Addition of "(Lecture)" and /or "(Lab)" #268
![image](https://user-images.githubusercontent.com/38253046/46313747-a80d2480-c596-11e8-9737-f93d0671b91a.png)

- [x] Placement of open course menu when multiple courses is incorrect in image below, follow mock up... Zeplin link: https://zpl.io/V41PrKJ

![image](https://user-images.githubusercontent.com/38253046/46313824-e0acfe00-c596-11e8-85b3-ed850cfcbb23.png)

- [x] Change "crosslisted" to "crosslisting in Course Menu

- [x] Course Menu should say "View Roster" for everyone except Visitor (this will change when Manage Roster feature added to release).
 
### FQA Script

1. User logs into Kits
2. User redirected to My Kits
3. Current semester courses loaded for user in ascending order by course number
4. User clicks current semester and selects a different term
5. My Kits reloaded with Kits from selected term in ascending order by course number
6. User types part of the course number in the search box and the list of kits is filtered
7. User types part of the course name in the search box and the list of kits is filtered

**Comment by swwalker** [comment]
@thegreenbot @LASHirsh is the prototype for this complete so we can close this issue?

**Comment by LASHirsh** [comment]
Will is still working on it.

**Comment by thegreenbot** [comment]
as of 07/12, I have not yet completed the <dialogue> component, or build out the pages detailing the workflow.

**Comment by swwalker** [comment]
Closing issue.  Feature has been tested and any bugs/enhancements have been documented as separate issues.
