### ISSUE TITLE
Sakai Integration

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#196]
- [x] outline goals of the integration
### Add app
1. Instructor clicks add app and selects Sakai from the app store
2. Kits checks if a sakai site with the roster id exists
3. Instructor taken to app setup screen 
4. Instructor edits available options
4. Instructor clicks done and sakai site created from selected template with kits users added

### Edit app

    **Not MVP1**
    #### Rename
    1. Instructor goes into kit edit mode
    2. Instructor renames the Sakai site and clicks done
    3. Kits updates the Sakai site name in Sakai

#### Toggle Visibility
1. Instructor goes into kit edit mode
2. Instructor selects Sakai to edit and taken to app setup screen
3. Instructor toggles visibility of app to students

#### Edit Label
1. Instructor goes into kit edit mode
2. Instructor selects Sakai to edit and taken to app setup screen
3. Instructor changes Kit label/display name

### Remove app
1. Instructor goes into kit edit mode
2. Instructor selects the option to remove Sakai
3. Kits removes all users in the kit from the Sakai site, Kits does not delete the site

- [x] map roles

Kits UI  Display | Kits Role | Sakai Role
-- | -- | --
Instructor | Leader  | Instructor
Assistant | Assistant | Teaching Assistant
Student | Participant | Student
Visitor | Visitor | Visitor

- [x] explore API's ability to accomplish goals
- [x] build a proof of concept

**Comment by ewendland23** [comment]
Would they ever want to choose an existing Sakai site or should we always create a new one?

**Comment by joliet** [comment]
When an instructor renames a Sakai site, does that just update the display in Kits, or does that rename the site in Sakai as well?

Does the Assistant role have access to grades?  Or are we thinking that would be determined at the application level and no grades would ever be present in Kits?

The Visitor role in Sakai is problematic and we've been talking about getting rid of it.  What does that role look like here?

**Comment by joliet** [comment]
I noticed there is no Course Builder role under Sakai roles.  This is a role we currently have.  What happens if that role doesn't map back to a role in Kits?

**Comment by swwalker** [comment]
Team meeting notes:

Librarians (Course Builder role in Sakai) should be Assistant roles.  New role in Toolkits to support solution for DKU.  TAs have some grade access; Course Builder does not.  90% of classes in Sakai don't use this role.

TAs have limited grade privileges in Sakai, can grade papers.  Is it an issue that Librarians would be able to see grades if they are assigned to Toolkits role.

Would it be sufficient for MVP1 to instruct those that use a course builder role to make that update in Sakai.

What happens if someone listed as an assistant in Kits is given the CB role in Sakai has a role change?  Does that change propagate to Sakai?  

With the launch of MVP1, the new roles will be used in both systems - the old roles will no longer be available in old toolkits.

Possible to add another function in Sakai to add librarians - batch add.  Only if this is the only tool where a one-off process is required.

**Comment by ewendland23** [comment]
I wish i knew how to comment on swwalker's comment about adding a query to determine if a sakai site exists.

I don't believe there currently is a way to search for a site with a given title using the Sakai API.
That means we can't automatically check if a sakai site exists for a given course.

@profmikegreene has said we could request that Longsight add an 'endpoint' that allows us to search for a site by **Title**.  

Question - is that the best thing to search or would **providerID** be better?  I also have that value for a course.

**Comment by profmikegreene** [comment]
@ewendland23 providerID is a much better route. I looked through the current endpoints and didn't see one that fits this use case. I'll write it up to Longsight and CC you. 

Do @noahhh or @outten45 want to be CC'd on that?
