### ISSUE TITLE
App Integration

### ISSUE THREAD

**Issue by bap13** [DukeLearningInnovation/kits#198]
### Description
Issue to capture overall app integration tasks as well as prioritization of specific tools.  Each task will be assigned milestones (delivery dates) individually.

### User Stories

- As an admin, I want to integrate new apps via the LTI standard so that I can use the most common integration standard for edtech integrations #107 
- As a developer, I want an open standard framework for integrating apps so that I can reduce long-term support and development costs  #108 
- As a leader, I select a tool and add it to my community so that members have access to it #140 
- As a leader, I want to hide tools from members so I can configure the tool before they access it #141
- As a leader or assistant, I want to add a tool to my community that I use to help teach the course but that students and guests/visitors/auditors never need to access or even know I'm using so that I can get to it easily #175

### Tasks
- [x] #221 Design app setup/provisioning screens for tools

Apps to be integrated in v1.0 milestone, in priority order:
- [x] #196 Sakai
- [x] #212 Sites@Duke (WordPress)
- [x] #170 Piazza
- [x] #213 Warpwire
- [x] #214 Box
- [x] #215 Email list (Sympa)
- [x] #217 Duke Wiki (Confluence)
- [x] #218 Duke Capture (Panopto)
- [x] #293  CIFS

Apps to be included in a later iteration
- [ ] #216 VCM
- [ ] #174 Qualtrics
- [ ] #219 VoiceThread
- [ ] #220 PlayPosit

**Comment by LASHirsh** [comment]
https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/85694996/simulate/sitemap?mode=i

**Comment by profmikegreene** [comment]
These are the apps I thought we were including in MVP1. @ewendland23 or others see issues with that?
Sites@Duke (WordPress)
Box
Duke Capture (Panopto)
Duke Stream (Warpwire)
Email list (Sympa)
Sakai
VCM
VoiceThread
Playposit
Piazza
Qualtrics
Add a custom URL

**Comment by ewendland23** [comment]
Issues I see:
1) I am not sure how much we are changing roles, so that may impact things a little.
2) VCM... We talked a little about how we could possibly use this, but we would need a concrete plan of how it would be incorporated.
3) Sakai... I think a different issue is tracking Sakai questions regarding where the Sakai site is set up?
4) I know we can do Qualtrics, but i haven't looked at the other three new ones nor have I seen a design or plan for what we'd want to setup for them.
5) Custom URL is completely different than any type of tool so far.  I think I already asked this elsewhere, but will we have other tools like it?  Where it is only seen by a subset of the community.

I guess we need more information about the new tools.  Can we get more information about how the tools will work?  Or maybe that is somewhere in here and i can't find it?

**Comment by profmikegreene** [comment]
CIFS is a currently app but not one listed above. I thought you posted this somewhere but I can't find the issue, @ewendland23 do you know how many course toolkits added CIFS in the past 2 years?

**Comment by curiousmustard** [comment]
I've prepared all logos (for App Store cards) & icons (for Kit cards) and placed in [Zeplin](https://app.zeplin.io/project/5b214027c1eddc64606dc242/screen/5b57787587d15b3364049724) & [InVision](https://projects.invisionapp.com/boards/VM3NU02FEDT/).

**Comment by profmikegreene** [comment]
Sakai, Wordpress, Box, and Warpwire integrations have been updated for review.

**Comment by ewendland23** [comment]
@profmikegreene  - I estimate we have had about 100 CIFS space set ups in the past 2 years.  Not common but when you need some mountable storage for a class, its about the only option?  Do you want to keep it or remove it?

The other thing is its very structured for Gus' classes.  A main, shared folder containing private folders for all members - admins and instructors can see, edit it all.

Keep?  Remove? Change?

**Comment by swwalker** [comment]
@profmikegreene - @ewendland23 let me know about the missing CIFS application for 1.0.  Looking at the thread on this issue, I do not see a final decision was made.  Should CIFS be added as an option for this release?  Let me know, and I'll make sure to include an issue and notify the team.

**Comment by profmikegreene** [comment]
I'm playing catch up, last I heard we all had pretty full plates for this release, if that's still the case, I think we should not add CIFS this release.

**Comment by profmikegreene** [comment]
Liz and I chatted, she thought it would be easier to keep it in rather than take it out. If @noahhh agrees, I'll have my team work up app details for CIFS.
