### ISSUE TITLE
Add/update/remove members within a community

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#199]
### Description

- Leaders and assistants in a community can add users to the community. See #37 for user experience flow.
- Leaders and assistants can change a community member's role. See #86 for user experience flow. 
- For course communities, leaders and assistants can remove users from a community. See #94 for user experience flow.
- Community membership can be exported to a CSV file.  See #109 

See #197 for functional decisions

### User Stories
- As a leader, I want to add a user not in the reference group because they are part of the learning community #37
- As a leader, I want to change a community member's role because they need different permissions than they previously had. #86 
- As a leader, I want to remove an individual or multiple users from the community because my community's membership includes only those who need access to the community and its tools.  #94
- As a leader, I want to view and edit my community membership and their roles so that I can determine if the group list and permissions need to be changed and update them as necessary, because the official course enrollment data from SIS does not include ad-hoc additions such as auditors, visitors, and TAs that I need to teach my course. #95
- As a leader, I want to export group membership to CSV so that I can import users into a non-integrated tool  #109 

### Tasks
- [ ] Identify metrics #178 

### Design QA Results
- [x] Roster should always default to "View Mode" first.  Instructor sees edit and view buttons, and then hit edit button to enter "edit mode" which shows the current edit roster UI.
- [x] EDIT MODE/PAGE: show a omnipresent message saying  "If you have trouble adding someone, try adding them here". Use an external-link icon, and open old-toolkits in a new tab.  (This is implemented, but formatting looks odd with another error notice (see below. Can the text in the green notice go below the "add New members area (and maybe not be green?)
![image](https://user-images.githubusercontent.com/38253046/47435163-01b9d680-d772-11e8-8931-04a6de252fe7.png)

- [x]  Display new view/edit buttons next to each other Zeplin link (desktop): https://zpl.io/VQEM7RR Zeplin link (mobile): https://zpl.io/a8NkWpQ
- [x] increase space between export a CSV file and DONE button to 20 px
![image](https://user-images.githubusercontent.com/38253046/46314779-7cd80480-c599-11e8-979f-799f0a13e872.png)
- [x] Searching for someone in name field - only shows name (not also netid/email)
       see UXPin wireframe:
![image](https://user-images.githubusercontent.com/38253046/46315294-0dfbab00-c59b-11e8-8e5a-c85f022539e2.png)

- [x] Email addresses should be netid@duke.edu (not first.last@duke.edu) and Onelink emails 
- [x] Default sort for roster should be: last name alpha(currently sorted by order added)
- [x] There are more results when you narrow down to "gre" than "gr"?
![image](https://user-images.githubusercontent.com/38253046/46315331-28ce1f80-c59b-11e8-95bc-f6ae39ed473a.png)
![image](https://user-images.githubusercontent.com/38253046/46315349-31bef100-c59b-11e8-9a50-0886db728248.png)

- [x] Error text when there are too many results to show needs to be changed. Currently is showing: "unable to find any results that match the current query". Change to something like "Too many results. Keep narrowing your search"
![image](https://user-images.githubusercontent.com/38253046/46361288-34712300-c63b-11e8-83d5-012cba52c7ef.png)

- [x] Roster: Styling off for Invite Dialog box: no close button, button text should be all caps, order switched
![image](https://user-images.githubusercontent.com/38253046/46361327-52d71e80-c63b-11e8-8970-cca295d67ca6.png)

- [ ] When this feature is added, community menu on My Kits should read "View/Edit Roster" for Instructors.

**Comment by swwalker** [comment]
#197

**Comment by swwalker** [comment]
@LASHirsh - consider adding a tooltip or some other means within the manage membership function to describe the assistant role (to distinguish between assistant and both instructor and student roles).  May also need to describe the differences between a visitor role and a student role

**Comment by swwalker** [comment]
Defer display of a profile picture in the roster to a future release, per team meeting.

**Comment by swwalker** [comment]
Functionality fully tested.  Bugs and enhancements to feature will be documented in separate issues.  Closing.
