### ISSUE TITLE
Voicethread Integration

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#219]
- [ ] outline goals of the integration
- [ ] map roles
- [ ] explore API's ability to accomplish goals
- [ ] build a proof of concept
