### ISSUE TITLE
PlayPosit Integration

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#220]
- [ ] outline goals of the integration
- [ ] map roles
- [ ] explore LTI ability to accomplish goals
- [ ] build a proof of concept

**Comment by joliet** [comment]
A faculty member in the Division of Marine Science and Conservation requested this app for Kits on 8/29/2109.
