### ISSUE TITLE
Message when no communities found for logged in user

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#223]
- [x] Provide message and treatment when no communities are found for the logged in user, given the filter criteria applied on the dashboard (Jen)

- [x] Update app accordingly (Noah/Will)

Related task: #188 

### Updates from Design QA

- [x] Message should display when searching on the My Kits page and search returns no results
- [x] Verified - PM

**Comment by swwalker** [comment]
current display:

![no courses associated with logged in user 080218](https://user-images.githubusercontent.com/38253046/43591609-b18c70da-9641-11e8-9fa8-c3759f0ff118.jpg)

**Comment by curiousmustard** [comment]
Mocked up an "empty state" treatment and added it to Zeplin. 
![screen shot 2018-08-02 at 10 58 52 am](https://user-images.githubusercontent.com/18170417/43592752-3b4cc1c4-9644-11e8-80d1-3e87503047e9.png)

**Comment by swwalker** [comment]
Closing issue - verified by Shellene Walker 11/13/18
