### ISSUE TITLE
Manage Community Private Custom Apps 

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#224]
### Description
Custom apps, when added, will be private (viewed only by the person who added the URL to their community view) by default.

Participant view only will be implemented for 0.3 release.  [participant view](https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/86103021/simulate/sitemap?mode=i)

### User Stories
1. As a member, I want to add custom URLs to my community view so that I can quickly access the websites/apps I use often, even though they are not community tools that everyone uses for the class #100 

### Questions

1. Name -how long? Does this appear under the little link Icon on the Kit card? #235 
2. URL - i assume this can be quite long #235 
3. Icon - do they get to supply this? #235 

### Tasks
**add custom url**
- [x] mockups
- [x]   front-end
- [x]   back-end

**edit custom url**
- [x]  mockups
- [x]   front-end
- [x]   back-end

**remove custom url**
- [x] mockups
- [x]   front-end
- [x]   back-end

explain to leader what this does and doesn't do (doesn't provision anything)
- [ ]  mockups - Lauren 
- [ ]   front-end
- [ ]   back-end

other tasks
- [x] customer icon picker to add and edit
- [ ] Define metrics to be captured #203 - Michael
- [x] Design verification
- [ ] [Sprint 14 Functional verification](https://docs.google.com/spreadsheets/d/1obU_rOQ09-WNwM1-P7lHMHZ0tf72dQ5xdz_i5YYUY7U/edit#gid=0)

### Tasks from Design verification
- [x] Error text "Limited to 18 characters" shorten line length & left-align assistive text (like text fields in components): Zeplin link: https://zpl.io/VDz7PgJ

![image](https://user-images.githubusercontent.com/38253046/46316253-a8f58480-c59d-11e8-83e1-9152851cff1f.png)

- [x] Edit App: Update message fades out so quickly it could not be read  - please slow down the alert message fade (see other bullet regarding notification styling).

![image](https://user-images.githubusercontent.com/38253046/46316110-2b317900-c59d-11e8-947d-94242d657740.png)

**Comment by swwalker** [comment]
Open questions from @ewendland23:

Can you explain the flow of adding one of these? What info will the user provide?

Name -how long? Does this appear under the little link Icon on the Kit card?
URL - i assume this can be quite long
Icon - do they get to supply this?
Sharing - This is a weird app - all other apps are shared with everyone in the community, right? So just this one is 'per user'? Or do you think it will be for a subset of the community at some point?

**Comment by swwalker** [comment]
Team meeting on 7/30/18:

Custom urls are either public or private.  If a community requires a custom url that is accessible to both instructors and assistants, then both need to add it themselves.

**Comment by swwalker** [comment]
Team meeting on 8/2/18:

Leaders and assistants have both the ability to add a custom URL for the entire community and the ability to add a custom url for their private use (see #100).  

Use cases:

- An instructor is using an app that is not currently available for integration.  The custom url should have the same administrative options that an app added through the kits app store has with regards to publish/unpublish (since there is no integration, roles/permissions in the target will not be managed by kits as it is in other apps)
- The instructor has added a custom url and wants their assistant to have access as well prior to it being published (available to the entire community)
- The assistant has added a custom url and wants the instructor to have access as well prior to it being published to the community.
- The instructor has added a custom url for their private use, but wants their assistant to have access to it as well

**Comment by LASHirsh** [comment]
Updates have been made to the custom link wireframes and approved by @curiousmustard 

- [custom link (instructor & delegate view)](https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/88545172/simulate/sitemap?mode=i)
- [custom link (participant view)](https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/86103021/simulate/sitemap?mode=i)

**Comment by swwalker** [comment]
From team discussion on 7/30/18: 
If a course requires a custom url and the instructor wishes to keep it unpublished for a period of time, the instructor would mark it as private.  If the assistant needs access before the full community is granted access, then the assistant will need to add the custom url to their own view of the community and mark it as private.  Once the custom url is ready for the entire community to see, then either the instructor or the assistant can mark the url as public.

**Comment by noahhh** [comment]
@bap13 For the custom URL, it displays both the Kit Name (limited to 18) and the input for the URL.  Should the URL input be the same length/styling as the Kit Name?

**Comment by LASHirsh** [comment]
@noahhh, I remember discussing that with both @curiousmustard and @bap13 . the URL input can be longer. @curiousmustard , if I'm remembering incorrectly, please correct me!

**Comment by curiousmustard** [comment]
@noahhh Nope, the thought was the line length would be indicative of character limitations (so shorter for Kit Name, longer for URL).

**Comment by swwalker** [comment]
Issue has been tested for release 1.0.  All bugs and enhancements to this feature will be documented in separate tickets moving forward.
