### ISSUE TITLE
View App Store 

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#228]
### Description
- browse the entire list of tools
- showcase featured apps
- get more info on tool

### User Stories

- As a leader, I want to browse a catalog of apps because I want to know what tools are available for teaching and learning and what they work well/can be used for. #48 

### Questions

- [ ] #182 What categories make sense to organize apps within the app store?

### Tasks

- [ ] #211 Define metrics 
- [ ] #256 Mobile 
- [x] #260 Differentiate between available and unavailable apps
- [x] Design verification
- [x] [Sprint 14 Functional verification](https://docs.google.com/spreadsheets/d/1obU_rOQ09-WNwM1-P7lHMHZ0tf72dQ5xdz_i5YYUY7U/edit#gid=0)

### Tasks from Design QA

- [x] Only show/list 3 "Featured Apps" so it does not break on two lines (currently hard coded in) - remove Qualtrics
- [x] When no kit is selected and user clicks on 'Add App', can "Select Kit" dropdown have an glow highlight (or the whole area highlight) and a "snackbar" display with text saying "A course needs to be chosen before an app can be added". - Zeplin link: https://zpl.io/a3lkedW
- [x] Make "select Kit" field always be width of side column (ie: same width as gray box below it)
![image](https://user-images.githubusercontent.com/38253046/46361932-e9580f80-c63c-11e8-8541-e46c17eaf36a.png)

- [x] Move definition (byline) of what app does closer to the App name
- [x] Update Category styles. Zeplin link: https://zpl.io/VYBeLgp 
![image](https://user-images.githubusercontent.com/38253046/46362015-27edca00-c63d-11e8-8801-3ed48d4e5560.png)

- [x] **Low priority** App page breakpoints: Can app boxes be more fluid like courses? Let's discuss. 
![image](https://user-images.githubusercontent.com/38253046/46362094-5ec3e000-c63d-11e8-91ad-87b72ad27bc6.png)

**Comment by bap13** [comment]
App page breakpoint editing is no longer an issue, we decided against it, so I closed the low priority QA item above.

**Comment by JustinJohnsen** [comment]
Provided potential app metrics from LI perspective in issue #211

**Comment by chrislorch** [comment]
On desktop:
"A course needs to be chosen before an app can be added" works when user clicks grayed out Add App button, but user only sees that feedback if scrolled to the top of the page. They don't see it if scrolled to bottom of middle/bottom of the page. Choosing Add app could scroll to top where they can choose the Kit.
Even better, kit choosing may scroll along with user progress down the page, so they don't need to flip back and forth 😃

**Comment by swwalker** [comment]
> On desktop:
> "A course needs to be chosen before an app can be added" works when user clicks grayed out Add App button, but user only sees that feedback if scrolled to the top of the page. They don't see it if scrolled to bottom of middle/bottom of the page. Choosing Add app could scroll to top where they can choose the Kit.
> Even better, kit choosing may scroll along with user progress down the page, so they don't need to flip back and forth

Added as enhancement request: issue #277

**Comment by swwalker** [comment]
closing feature issue.  Remaining work to be done on this page is identified by other open issues.
