### ISSUE TITLE
View Community Membership

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#238]
### Description
For a given course community, an authenticated user can view community membership.

- Community members with leader, assistant or student roles can view community membership.  Visitors can not view community membership.

- Suppressed information (FERPA-protected) will not be displayed.  Display of suppressed information for certain roles in a community will be addressed by a future enhancement.

- Profile pictures will not be included and will be addressed by a future enhancement. #176

### User Stories

1. As an authenticated user, I want to see a list of the other users in my communities, so that I can know who is in my communities and what their roles are #96
2. As a leader, I want to view the members of my community so I know the membership is accurate #245
3. As a system, I need to control and process data in a way that is FERPA compliant so that we remain in good legal standing. #156  

### Tasks
- [x] Verify members added in Tookits can be displayed in the community roster in Kits #240 
- [ ] Mobile  #255
- [x] Design verification
- [ ] Functional verification

### Updates from Design QA
- [x] Non-instructor roles only see "View mode", and the page does not have any icons.
- [x] Remove status column (for now, may be added back at a later date)

**Comment by swwalker** [comment]
Closing issue.  Feature has gone through first round of testing and results have been documented in additional issues.
