### ISSUE TITLE
View App Details (styling)

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#239]
### User Stories
As a leader, I want to browse a catalog of apps because I want to know what tools are available for t
teaching and learning and what they work well/can be used for. #48

### Tasks

- [x] Proof-of-concept for managing app details content #242 
- [x] unable to access tool via link provided - Will to troubleshoot and notify Lauren/Michael 
- [x] apply styles as defined in Zeplin: zzpl://screen?sid=5b47a9632cf9d1457da8d779&pid=5b214027c1eddc64606dc242 
- [x] add Sakai app content

**Comment by swwalker** [comment]
@profmikegreene:

There are two existing issues that relate to your comment above:

#76 poses the question about building in a rating system for apps
#182 addresses the need to categorize/group apps, likely for both display and search purposes

Both issues have been tagged to be prioritized for a future release.

**Comment by thegreenbot** [comment]
1st pass is complete, and @curiousmustard has had a look at it. I've also gone through the content on the prod instance (kitscontent.cloud.duke.edu) to clean it up a bit. As soon as kits points at https://kitscontent.cloud.duke.edu/rest/resources for the app detail content, stuff should look much better.

**Comment by noahhh** [comment]
@thegreenbot could you add the resource_id to https://kitscontent.cloud.duke.edu/rest/resources like it is on https://dws-d70.oit.duke.edu/rest/resources?  I can make the switch after that.  Thanks!

**Comment by curiousmustard** [comment]
After looking more closely, I think there needs to be more space between the sections, particularly when content stacks on smaller devices. Maybe like 20-30px? @thegreenbot @swwalker 
<img width="342" alt="screen shot 2018-12-17 at 9 52 58 am" src="https://user-images.githubusercontent.com/18170417/50094924-4c8c2380-01e2-11e9-8ae0-a3480ebe3d9a.png">

Everything else looks good with styling of App Details!

**Comment by bap13** [comment]
Waiting to hear this has been pushed to kits-test for final review.

**Comment by thegreenbot** [comment]
putting a top margin on h2s. This is committed and pushed to the tk2 branch
