### ISSUE TITLE
Implement display changes when add/edit/delete app options selected for a community

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#243]
https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/85923515/simulate/sitemap?mode=i

### Updates from Design QA
- [x] Delete the icon immediately, even if the action is still happening in the background (ex: delete a VM). No "deleting" state on front end is needed
- [x] Center trash can in red circle, please.
- [x] Exiting delete mode
       First choice: Red cans go away when you click anywhere off of the card
       Second choice: replace menu icon with Done button (Jen can provide) while in Remove App state

- [x] Adding an App: Have app icon show at 50% opacity until resource is set up.
![image](https://user-images.githubusercontent.com/38253046/46314944-02f44b00-c59a-11e8-925d-8793eea322dc.png)

- [ ] **LOW PRIORITY** Can we add corresponding icons to this menu for edit, remove, and add? 
![image](https://user-images.githubusercontent.com/38253046/46362221-aa768980-c63d-11e8-819d-4c2b93d4a79a.png)

**Comment by outten45** [comment]
assigning to @noahhh. he is going to get some of the route/controllers/view setup for @thegreenbot on the front.

**Comment by swwalker** [comment]
Design team to verify language

**Comment by LASHirsh** [comment]
@noahhh , here are the three:

<img width="976" alt="screen shot 2018-09-27 at 3 40 01 pm" src="https://user-images.githubusercontent.com/2487713/46170893-0e2f3a00-c26d-11e8-9416-26c372f137a6.png">

Let me know if you have questions!

**Comment by noahhh** [comment]
Will be available for testing when we push to acceptance next meeting (Oct. 4th)
