### ISSUE TITLE
Write UX test scripts for Release 1.0

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#248]
### Description
Plan for obtaining feedback from user community 

###Features
#232 Create Course Communities
#188 View My Course Communities
#234 Access Course Community Apps
#238 View Community Membership
#224 Manage Community Custom Private Apps
#228 View App Store

### Tasks 
_(tasks will be added as features are ready for review)_
**#232 View My Course Communities**
- [ ] write toolkits 1 scripts
- [ ] write kits scripts

**#234 Access Course Community Apps**
- [ ] write toolkits 1 scripts
- [ ] write kits scripts

**#238 View Community Membership**
- [ ] write toolkits 1 scripts
- [ ] write kits scripts

**#224 Manage Community Custom Private Apps**
- [ ] write toolkits 1 scripts
- [ ] write kits scripts

**#228 View App Store**
- [ ] write toolkits 1 scripts
- [ ] write kits scripts

**Comment by profmikegreene** [comment]
Lauren and I met with LTS team today to discuss testing. Notes below.

Testing should be broken into 3 states, design qa (DQA), functional qa (FQA), and ux testing (UXT). Some draft workflows for the project team to poke holes in below.

## DQA
- [x] design testing workflow
1. Design is deployed in qa environment, when issue found
1. tester creates GitHub issue with
    1. description of issue
    1. screenshot
    1. description of desired change
    1. rational for change
1. dev team reviews issue, gets clarification, assigns it
1. dev fixes issue, reassigns to tester and adds verification label
1. tester verifies fix and closes issue

? How small or large before the process doesn't work

- [ ] craft examples
- [ ] add `verification` label

## FQA
- [x] design testing workflow
1. feature is deployed in qa environment, when issue found
1. tester creates GitHub issue with
      1. test script id
      1. screenshot optional
      1. description of what's broken and expected behavior
      1. error handling info if presented
      1. browser/os?
1. dev team reviews issue, gets clarification, assigns it
1. dev fixes issue, reassigns to tester and adds verification label
1. tester verifies fix and closes issue

? How to test with fake data to pre-create use cases and streamline testing

- [ ] write toolkits 1  and kits scripts
- [ ] craft examples

## UXT
- [ ] LH/JH spend 2 hours updating sketch/uxpin for this round of testing
- [ ] MG recruit testors
- [ ] design testing workflow

## unauthenticated user experience
- [ ] wireframe
- [ ] content
- [ ] mockup

* kits.duke.edu/
    * marketing page
    * audiences
        * non-duke - 200
        * duke unauthenticated - 200, show mykits dropdown
        * duke authenticated first-time - 200, show mykits dropdown, show tutorial
        * duke authenticated returning - 200, show mykits dropdown
* kits.duke.edu/mykits
    * audiences
        * non-duke - shib redirect
        * duke unauthenticated - shib redirect
        * duke authenticated first-time - shib redirect
        * duke authenticated returning - shib redirect
* kits.duke.edu/apps or /appstore
    * audiences
        * non-duke - 200
        * duke unauthenticated - 200, show mykits dropdown
        * duke authenticated first-time - 200, show mykits dropdown, show tutorial
        * duke authenticated returning - 200, show mykits dropdown
* kits.duke.edu/about
    * audiences
        * non-duke - 200
        * duke unauthenticated - 200
        * duke authenticated first-time - 200
        * duke authenticated returning - 200
