### ISSUE TITLE
Design QA - Global Updates

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#259]
### Header

- [x] Increase "Kits" title to 30 px, and reduce margin to 10 px
- [x] Remove Duke logo link to Duke University - entire name should link to kits home page
      
![image](https://user-images.githubusercontent.com/38253046/46315690-17d1de00-c59c-11e8-8338-09c1643cc1d0.png)

- [x] Add "kits" title to open menu
- [x] Unlink Duke logo.
- [x] Add more space in between items (above Account settings)
![image](https://user-images.githubusercontent.com/38253046/46315709-23250980-c59c-11e8-85b5-11a6e73d09a0.png)

### Errors

- [x] Error message should be on top of all text on the page 
- [x] Edits to Snackbar: adding color for error states and make container 60px tall. Zeplin link: https://zpl.io/2pO6Ejo- [ ]

See image below for example from Add New Members.  Verify this does not occur in other pages/scenarios throughout the app:

![image](https://user-images.githubusercontent.com/38253046/46369703-b704dd00-c651-11e8-9bbe-e7799e56c67b.png)

- [x] "Cancel" button styling incorrect (button should be outlined) Zeplin link: https://zpl.io/VOkmwXr
- [x] Increase space between buttons to 20px
![image](https://user-images.githubusercontent.com/38253046/46316336-e6f2a880-c59d-11e8-8a51-d65365cdaa81.png)

**Comment by bap13** [comment]
Re-reviewed all these items and they are all fixed. Closing/ completing this issue.
