### ISSUE TITLE
Change visual display of app if it is not available to be added from the app store

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#260]
### Description
To differentiate between apps in the app store that an authenticated individual can add to a community and ones that are "Coming Soon", need to have different visual and behavior on click.

### Use Cases

- [x] No community is identified (see issue #228)
- [x] Integration of app in Kits is underway ("Coming Soon")
- [x] Only one instance of the app is permitted per community and the app has already been added (see issue #265)

### Tasks

- [x] Design specs for apps that are currently unavailable but should still be displayed in the app store
- [x] Implement design and prevent user from adding apps that are not available
- [ ] Design QA 
- [x] Functional QA

**Comment by swwalker** [comment]
@profmikegreene - This ticket has been added to Triage in Sprint 14.  Letting you know so you can prioritize it with the other open items in the To Do and Triage lists.

**Comment by LASHirsh** [comment]
just adding a note here that the Coming Soon banner has been applied to some but not all of the apps we already determined will not be in this release: banner still missing from VCM and VoiceThread. (others tbd during testing)
