### ISSUE TITLE
About Page (styling)

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#261]
### Description
About page contains general information about Kits.  It is accessed via a link in the toolbar across all pages in Kits.

### Tasks

- [x] Implement feature to ingest formatted content into Kits app #242 
- [x] Create formatted content
- [x] Font should be 16px line-height: 24px; #262626 for Body. Headings should be Duke Blue 
- [ ] Apply Zeplin styles
- [x] Pull content from drupal

**Comment by thegreenbot** [comment]
1st pass is complete, and @curiousmustard has had a look at it. I've also gone through the content on the prod instance (kitscontent.cloud.duke.edu) to clean it up a bit. As soon as kits points at `https://kitscontent.cloud.duke.edu/rest/resources` for the app detail content, stuff should look much better.

**Comment by bap13** [comment]
12/17 - ABOUT page: not sure where this task is because the check marks above are checked, but the styles from Zeplin have not been applied, nor are headers correct - so I unchecked them above. Has it been completed but not pushed? If so, can it please be pushed today to test?
Web link to styles: https://zpl.io/V41rdry
Zeplin app link to Styles: zpl://screen?sid=5b4786e3c18fd03c7e9622f7&pid=5b214027c1eddc64606dc242

**Comment by thegreenbot** [comment]
styles are committed and pushed to the tk2 branch
