### ISSUE TITLE
Determine how to manage available roles across both Kits and Toolkits.

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#269]
### Description
The new Kits app has limited the number of roles available within a community in an effort to simplify the role management process and make it more easily understandable by Kits users.  Because both Kits and Toolkits are using the same base code, there will be an inconsistency in how roles are applied to a course community, depending on how the course is first created for use by Toolkits/Kits.  

For example, if a student logs into Kits before the course has been created in Sakai, the Kits roles will be assigned, not Sakai/Tookits roles.

All courses created as Kits (CV4) after production launch, keep prior created courses as Toolkits (CV1)

- All projects and non-sis course created as CV2
- All outside of current term courses created as CV5 (copy of CV4 roles), keep prior as CV3
- Sakai::Add Participants still Toolkits UI
- Kits::Manage Roster shows CV1 roles for kits created prior to launch
- Should be ready for testing in 2 weeks - 10/24/18

### Tasks

- [x] Do we have to customize site info :: participant list?
- [x] Do we have to modify Sakai roles?
- [x] Add in app communication about role changes in Toolkits and Kits for production launch

**Comment by swwalker** [comment]
10/12/18 Notes from discussion on approach: https://duke.app.box.com/notes/329191811002

**Comment by chrislorch** [comment]
@ewendland23 thanks for the description of the CVs
1: Original Toolkits for Courses (12 groups including ‘all’)
2: ‘Adhoc’ Toolkits – normally these are for departments or for project sites.  User can prepend with adhoc_, duke_ or project_
3: ‘Non-Sis’ Toolkits – we had to add these because Sakai had some really old courses inherited from Blackboard.  We didn’t have the current SISS data for these since SISS only gives us a year’s worth of class info.  They match CV1 in every way except the student and faculty roles are editable and not pulled from the original roster.
4: ‘Kits’ Toolkits – new kind of Course toolkit with fewer roles
5: ‘Kits Non-Sis’ – what we will use for older courses going forward.  It will have the limited number of roles to match CV4.
 CV5 is not added yet to Kits / Dev

**Comment by chrislorch** [comment]
_Do we have to customize site info :: participant list?_ No, this seems inadvisable until kits/toolkits provides the same info that the participant list does. That's many MVPs away.
_Do we have to modify Sakai roles?_ - No, we will remove course builder from roles in site template. If folks ask about course builder we can point to the communication that suggests using Teaching Assistant, which has the same permissions. 
_Add in app communication about role changes in Toolkits and Kits for production launch_ - Draft: Starting for Spring 2019 courses, user roles in **Site Info > Add Participants** are simplified to improve user workflow and integration with other Duke tools. Teachers have 5 roles that more closely reflect the needs of the Duke community. No change to previous courses is required on your part.

You will only see these options in future courses - previous semester courses are not affected. Please see this article for more information [which has old role names/mapping, to be deprecated over time].
Message of the day / Liz may add as Tooltip.

**Comment by chrislorch** [comment]
Reassigning to @ewendland23 for confirmation when CV options are ready - please update us when we are ready to test all of these roles/Add participants options on dev. We can keep working on #257 regression script.

**Comment by ewendland23** [comment]
Reassigning to @chrislorch - CV5: kits_non_sis_course is ready on toolkits-dev.
