### ISSUE TITLE
Navigation from community membership page

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#286]
### Features
#199 Add/update/remove members within a community
#238 View community membership

### Description

- [x] The Done button on the edit roster page should return the user to view roster/last page 
- [x] "Back" on the roster page, whether in view or edit mode, should return the user to the My Kits page
- [x] Update "Back" to "Back to My Kits"

**Comment by swwalker** [comment]
Confirmed 11/26/18

**Comment by swwalker** [comment]
unable to recreate
