### ISSUE TITLE
CIFS Integration

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#293]
### Description
Allow a CIFS space to be provisioned for a community
Currently enabled in Toolkits.
See discussion in issue #198 App Integration

### Tasks

- [x] Define default icon for CIFS space (Barb/Jen)
- [x] Add app to app store (Noah)
- [x] Define app details for app (Michael)
- [x] Functional QA

**Comment by curiousmustard** [comment]
Created CIFS App store card and App icon images and placed into Zeplin: https://zpl.io/V1q44GJ

**Comment by noahhh** [comment]
@profmikegreene 

When you have time, could you provide the byline and categories for CIFS?
Will CIFS be featured?

**Comment by profmikegreene** [comment]
@noahhh CIFS will not be featured. 
Categories: storage 
Byline: Save files and directories on reliable network storage.

Other content on https://dws-d70.oit.duke.edu/node/85 resource_id: CIFS 
can change if necessary.

**Comment by swwalker** [comment]
closing issue.  All bugs/improvements will be documented in a separate issue.
