### ISSUE TITLE
App integration bugs from 11/30/18

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#321]
### Needs Testing
- [x] Problem with Sakai Batch (old toolkits)  Jolie can test once this is fixed. #278

### Verified complete
- [x] Box sites have wrong URL
- [x] Blogs/Sites@Duke: we are pointing at a non-existent host on Test.  Point at sites-dev so we can test.
- [x] Problem with adding a Sakai App
       Starting to add an app and hitting "cancel" before finishing does not actually cancel adding the app. It shows up on the Kit regardless. 
- [x] Warpwire - I added the Warpwire app to CEE 301L - 001 F18 and clicking on it got me the html code behind a 404.
![image](https://user-images.githubusercontent.com/38253046/49306572-9e257600-f4a0-11e8-84b8-43fb8b0dc40e.png)
- [x] Sakai Roles – Kits Assistant should map to Sakai Teaching Assistant
- [x] Sympa problem outlined by Heather in Teams: When I clicked on the Sympa app in CEE 301L - 001 F18, Shouldn't I be logged in (shib transferred)? And after login, I see a number of admin options, but I don't see where to create an email. This could be that Sympa is confusing. But perhaps someone who knows the application can say if this is what it should look like?
- [x] Wiki also had issues 
        I added the Confluence Wiki app to CEE 301L - 001 F18. But when I clicked on the app I got "Page not found". 
![image](https://user-images.githubusercontent.com/38253046/49306656-db8a0380-f4a0-11e8-8d7f-80ab5efccf9f.png)
- [x] Jolie found a problem in Old Toolkits setting up a OneLink account – it created the account but gave an error message
- [x] Barbara found a problem in old toolkits where it showed blanks for warpwire roles

**Comment by hrvalli** [comment]
I’ve checked again. When I click on Sympa I go to a page that—as far as I can tell—does not let me send an email. And when I click on “More details” for Sympa in the App store, I get an error saying “We’re sorry. Something went wrong". (See attached).

Best,

Heather V.

**Comment by ewendland23** [comment]
@hrvalli  - Sympa doesn't provide a way to send an email.  The link just lets you see information about the Email list and an archive of messages sent to it.  I wonder if the designers have an idea about how users will want this to work - should we provide an email link with the list as the address instead?  @profmikegreene @LASHirsh ?

**Comment by profmikegreene** [comment]
@joliet @chrislorch please test batch create on Monday.
