### ISSUE TITLE
As a leader, I want to add a user not in the reference group because they are part of the learning community

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#37]
- [ ] search for user my netid
- [ ] search for person by name
- [ ] search for person by DUID
- [ ] search for person by email
- [ ] trigger onelink invite for users not found

Stretch
- [ ] search for grouper group

**Comment by JustinJohnsen** [comment]
Will they ever need to merge back with the reference group? Will we need to worry about versioning with the rosters?

**Comment by profmikegreene** [comment]
@ewendland23 what do you think about Justin's questions? How is this handled now, particularly during add/drop?

**Comment by ewendland23** [comment]
If I understand the question - @JustinJohnsen is asking if we would update the SISS roster?  I don't think we would ever do that.  And we have never needed versions - we do keep track of who adds whom and when if we ever need to untangle things but I don't think we have ever used that ability.

Let me know if I am misunderstanding the question.

**Comment by swwalker** [comment]
closed - incorporated in #199
