### ISSUE TITLE
As a leader, I want to add custom URLs to a community so that we can use a tool that isn't in the app store

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#39]
add custom url
- [ ] mockups
- [ ] front-end
- [ ] back-end

edit custom url
- [ ] mockups
- [ ] front-end
- [ ] back-end

rename custom url
- [ ] mockups
- [ ] front-end
- [ ] back-end

explain to leader what this does and doesn't do (doesn't provision anything)
- [ ] mockups
- [ ] front-end
- [ ] back-end

remove custom url
- [ ] mockups
- [ ] front-end
- [ ] back-end

Stretch
- [ ] add custom url to multiple communities at once
- [ ] system searches app store to ensure the custom url isn't already integrated with the system
- [ ] upload a file as a custom url

**Comment by JustinJohnsen** [comment]
Is there any differentiation (or need to do so) between apps vs. websites vs. media (vs. other)? Faculty will definitely need the ability to link to external resources. Is this a different thing?

**Comment by profmikegreene** [comment]
If possible to sustain, I hypothesize the best UX would be a single text field that accepts any URL and we figure out what to do with it on the backend. If we had a process to review all the custom URLs regularly, we could continue to make sure they did what faculty expect when they paste them in.

This is part of what I'm trying to get at with https://projects.invisionapp.com/d/main#/projects/boards/5767824/173123001 FURL is the technical piece of it.

**Comment by swwalker** [comment]
closed - incorporated in #224 and #236
