### ISSUE TITLE
As a leader, I want to configure an app for my course because integrations need to be more complex than on/off and group member access in order to provide significant value to me.

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#45]

**Comment by JustinJohnsen** [comment]
It isn't entirely clear to me what 'configure an app' means. Can someone provide an example or more context?

**Comment by profmikegreene** [comment]
One example is any tool that supports LTI deep linking, PlayPosit is the first one we've deployed. The faculty goes through choosing the piece of content they want to share as part of the setup process - doesn't stop after enabling Playposit. Chris or I can show you the workflow.

**Comment by LASHirsh** [comment]
Some questions for you:

- [ ] How can we break this one down? What does "configure an app" mean for the apps in the list of tools that were proposed for V1? What are you envisioning for each and is each step essential?
- [ ] Exactly how much more complex do you believe it would need to be to provide value (and how are we defining that)? And is that kind of complexity truly scalable and sustainable? 
- [ ] How might we go about testing this assumption? 

I don't disagree that faculty would find it valuable to be able to do more than just turn a tool on for a course from within this site. I suspect (and would also recommend), however, that the initial focus (version 0.1) in terms of "configuring an app" will need to be on provisioning learning community access to the tools and making sure that is working well for the new tools before going beyond this.

**Comment by profmikegreene** [comment]
For the scope of MVP1 'configure' is defined as 'provision' which is defined as create a course space in the tool and add the membership to the course space.
