### ISSUE TITLE
Suggest new app for App Store

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#47]
### Description
A button on the app store page will link to a Qualtrics form to be completed by the user.

### User Stories
As an authenticated user, I want to suggest a new app for the app store because I think it meets the criteria for evaluation.

### Potential enhancements
see suggested apps for admins and content managers
workflow for communicating to the user that suggested the apps that it has been reviewed
list of suggested apps and their status for authenticated users

### Tasks

- [x] Create Qualtrics form and workflow https://duke.qualtrics.com/jfe/form/SV_3CL87r0ejwkM0Kh
- [X] Add link to Qualtrics form on App Store page
- [x] Clarify purpose of request on Qualtrics form, see #287

**Comment by JustinJohnsen** [comment]
Is this really core to MVP1? This feedback will be very helpful, particularly to curating and expanding the ecosystem, but I'm not sure it is critical to the initial product.

**Comment by JustinJohnsen** [comment]
If we pull in feedback from community members, will there be any important factors to weigh the value of the feedback? Would we value more the feedback on apps from a faculty vs. student? Would we value more the feedback from a dean vs. provost?

**Comment by profmikegreene** [comment]
I've teetered back and forth on MVP 1 vs 2 on this one. The hypothesis that it's going to bring us so much value tends to escalate it I think.

My assumption is the criteria for evaluating the feedback uniformly would be arbitrary, but I haven't thought deeply on this. It may be helpful to create such a rubric and use in our discussion, I worry about designing an algorithm to make the decision for us though.

Possible criteria
* number of votes by role over time
* is it licensed at an enterprise, school, or department level
* there are going to be many criteria under /cms that relate to this, but I've kept them separate in my mind. Could be time to stop that.
  * SAML/Shib
  * LTI
  * WCAG2.0

**Comment by profmikegreene** [comment]
It seems part of the solution to this question from the problem statement though, no?

> How might learn.duke improve this to accommodate the entire range of learning communities, those that use a single tool, those using multiple supported tools, and those using their preferred, unsupported tools?

**Comment by JustinJohnsen** [comment]
I guess this highlights a crux for me about how we manage MVP1. Are we trying to do a light version of all the things we expect to include in the final product, then iterate until we're happy? Or do we try to find a viable minimum set of features and do that part well enough to 'nail it down' then build on that until we reach a full feature set?

**Comment by hrvalli** [comment]
I'm inclined toward the latter. I think buy-in will be important, and it's better to do whatever we're doing as well as possible, so people will see it as a solid—if limited—product. Then we'll generate good will that would help support us as we add on further features. Basically, I think it's better to do six necessary things very well than a dozen things in a lesser manner.

**Comment by profmikegreene** [comment]
Other potential evaluation criteria
* app is something that has been of tremendous value to my courses and/or my department and/or my school
* I have data to suggest it will be used often by others.
