### ISSUE TITLE
As a leader, I want to browse a catalogue of apps because I want to know what tools are available for teaching and learning and what they work well/can be used for.

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#48]
MVP1
- [ ] browse the entire list of tools - see #228 View App Store
- [ ] showcase featured apps - see #228 - View App Store
- [ ] get more info on tool - see #229 View App Details

Because we have so few apps at the start, the following features have been moved to a Future Release - see #253 - Search for apps in App Store
- [ ] faceted search 
- [ ] filter by category
- [ ] sort by name
- [ ] sort by category

**Comment by hrvalli** [comment]
At some point (perhaps later in the process) I'd like to see mockups of what the different search options look like—how the instructors get to them, how they choose among them to reach their desired information.

**Comment by hrvalli** [comment]
As I think on this, it occurs to me that we're in a building full of librarians, who mostly specialize in connecting people with the information they're looking for. Perhaps we could work with one of them to establish the best possible information organization.

**Comment by JustinJohnsen** [comment]
![img_180103112443610](https://user-images.githubusercontent.com/13791075/34529076-d556aa86-f078-11e7-823b-2181832e1cee.jpg)

**Comment by profmikegreene** [comment]
@hrvalli great idea. I'll reach out to a few folks and ask if anyone comes to mind.

**Comment by joliet** [comment]
I know these are just suggestions, but I wonder if the options on cost and user limit would be confusing.  Cost to whom? I wonder how many faculty would even choose anything other than free. I  wonder if it would be more helpful to have a "find more options" that would include paid options. Depending on the scope of how this would ultimately be used, I can see how user limit would be helpful.

As long as the tools have the appropriate metadata attached to them, instructors should be able to find the right tool match through search.

**Comment by profmikegreene** [comment]
I see your point @joliet, most of our apps are free for faculty and come with unlimited use. I could see a potential scenario where we have good enough workflows to incorporate projects from the R&D team which may have pricing and user limits. We haven't discussed anything like that though, so there are tons of unknowns.

**Comment by profmikegreene** [comment]
@profmikegreene add procurement rubircs stuff here

**Comment by profmikegreene** [comment]
An app details content example can be found at https://github.com/DukeLearningInnovation/learn.duke/blob/master/docs/apps/Sites%40Duke.appdetails.md 

Thoughts/changes @DukeLearningInnovation/learning-innovation

**Comment by JustinJohnsen** [comment]
A bunch of the middle text seemed out of place, about Duke's approach to tech rather than about Sites@Duke. The pedagogy section obviously is incomplete. Are you looking for contributions or proofreading?

Justin Johnsen
Learning Technology Analyst
Duke Learning Innovation

________________________________

**Comment by profmikegreene** [comment]
Contributions mostly at this time @JustinJohnsen. I added topics we've discussed in the past but don't know what is/isn't useful to users or sustainable for us to maintain. I'll pull some if this content out of this example page and onto https://github.com/DukeLearningInnovation/learn.duke/blob/master/docs/cms/about.md#how-do-apps-get-added-to-the-kits-app-store for clarity

**Comment by swwalker** [comment]
closed - incorporated into separate feature issues
