### ISSUE TITLE
As a leader, I want to change a community member's role because they need different permissions than they preciously had.

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#86]
- [ ] select user or multiple users to edit
- [ ] select new role
- [ ] ask user to confirm changes
- [ ] save changes
- [ ] changes to the permissions are reflected in browser upon refresh so community members don't have to log out and back in to see changes.

**Comment by swwalker** [comment]
closed - incoporated in #199
