### ISSUE TITLE
As a leader, I want to remove access to a tool I have added to my course and delete it from my course view because we don't want to see tools we are not using.

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#91]
- [ ] select tool or multiple tools to edit
- [ ] choose to remove
- [ ] ask user to confirm removal
- [ ] save changes and de-provision
- [ ] changes to the permissions are reflected in browser upon refresh so community members don't have to log out and back in to see changes.

**Comment by profmikegreene** [comment]
Does this also include deleting the assets/course space that was created when the tool was added?
When I remove sites@duke from my course, am I deleting the site or not?

**Comment by profmikegreene** [comment]
Does deprovision also mean delete the assets? Could we separate the turn off access action from the system delete the assets action in case someone really doesn't know what they're doing? Perhaps a 30 day window where an admin (or leader eventually) could reanable a tool they had previously deleted and the content would still be there.

**Comment by swwalker** [comment]
Closed - information incorporated in #201
