### ISSUE TITLE
As a leader, I want to remove an individual or multiple users from the community because my community's membership includes only those who need access to the community and its tools.

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#94]
- [ ] select user or multiple users to edit
- [ ] choose to remove
- [ ] ask user to confirm removal
- [ ] save changes
- [ ] changes to the permissions are reflected in browser upon refresh so community members don't have to log out and back in to see changes.
- [ ] users in SISS reference group cannot be removed and UI is presented to leaders who attempt to do so

**Comment by swwalker** [comment]
Closed - incorporated in #199
